"""Common behavioral interview prompts with concise STAR-answer guidance."""

BEHAVIORAL_QUESTIONS = [
    ('Tell me about yourself.', 'Give a 60–90 second professional summary: present role, relevant past experience, and why this opportunity fits.'),
    ('Why do you want this role?', 'Connect the role’s work to your demonstrated strengths, interests, and a specific contribution you want to make.'),
    ('Why do you want to work here?', 'Mention researched company details, then explain why the mission, product, or team matches your goals.'),
    ('What are your greatest strengths?', 'Name one or two job-relevant strengths and prove each with a short, measurable example.'),
    ('What is a weakness you are working on?', 'Choose a real, non-essential weakness and explain the concrete habit or feedback loop improving it.'),
    ('Tell me about a difficult problem you solved.', 'Use STAR: describe the stakes, your diagnosis, the action you owned, and the measurable result.'),
    ('Tell me about a failure.', 'Own the outcome without excuses, explain what changed afterward, and show evidence of the lesson applied.'),
    ('Tell me about a mistake you made.', 'Choose a contained mistake, state how you corrected it promptly, and explain the prevention you introduced.'),
    ('Tell me about difficult feedback you received.', 'Show that you listened, clarified expectations, acted on the feedback, and improved over time.'),
    ('Tell me about a conflict with a coworker.', 'Focus on respectful direct communication, shared facts, and the solution rather than blaming the person.'),
    ('Tell me about a disagreement with your manager.', 'Explain your evidence-based perspective, how you voiced it professionally, and how you supported the final decision.'),
    ('Tell me about working with a difficult teammate.', 'Describe boundaries, empathy, direct communication, and the specific outcome for the work.'),
    ('Tell me about a time you led a team.', 'State the goal, how you aligned people and removed blockers, and the team result.'),
    ('Tell me about a time you showed leadership without a title.', 'Show initiative: identify a gap, influence collaborators, execute a solution, and quantify impact.'),
    ('Tell me about a time you motivated others.', 'Explain what the team needed, how you created clarity or recognition, and the change in delivery or morale.'),
    ('Tell me about a time you delegated.', 'Describe matching work to skill, setting clear outcomes and checkpoints, and retaining accountability.'),
    ('Tell me about a time you took initiative.', 'Show a problem you noticed independently, the practical action you took, and its result.'),
    ('Tell me about a time you went above and beyond.', 'Choose an example with meaningful impact, while showing you managed priorities responsibly.'),
    ('Tell me about a time you had to learn something quickly.', 'Describe your learning plan, how you validated understanding, and how you applied the new skill.'),
    ('Tell me about adapting to change.', 'Explain the change, how you reprioritized and communicated, and what improved because of your response.'),
    ('Tell me about working under pressure.', 'Use a high-stakes example; emphasize prioritization, calm communication, and the outcome.'),
    ('Tell me about managing competing priorities.', 'Explain your prioritization criteria, stakeholder alignment, tradeoffs, and final delivery.'),
    ('Tell me about meeting a tight deadline.', 'Describe scope decisions, a focused execution plan, status communication, and the delivered result.'),
    ('Tell me about a time you missed a deadline.', 'Own the miss, explain early communication and recovery steps, and name the process change that prevented repeats.'),
    ('Tell me about a time you improved a process.', 'Quantify the old pain point, describe the improvement, adoption plan, and saved time, cost, or errors.'),
    ('Tell me about a time you used data to make a decision.', 'Name the question, data source, analysis, decision, and measurable business or user outcome.'),
    ('Tell me about a time you made a decision with incomplete information.', 'Describe the risks, assumptions, reversible next step, stakeholder communication, and learning afterward.'),
    ('Tell me about an ethical dilemma.', 'Explain the principle at stake, who you consulted, the responsible action, and how you documented or escalated it.'),
    ('Tell me about a time you advocated for a customer.', 'Show how you learned the customer need, influenced a decision, and improved the user experience.'),
    ('Tell me about a time you handled an unhappy customer.', 'Listen, clarify the issue, set expectations, resolve what you can, and share the prevention lesson.'),
    ('Tell me about a successful collaboration.', 'Describe complementary roles, shared planning, communication habits, and the joint result.'),
    ('Tell me about working with a cross-functional team.', 'Explain how you translated priorities across functions and resolved dependencies to deliver.'),
    ('Tell me about influencing someone without authority.', 'Use evidence, understand their incentives, build trust, and explain the agreement reached.'),
    ('Tell me about giving constructive feedback.', 'Describe private, specific, timely feedback focused on behavior, plus support for improvement.'),
    ('Tell me about receiving an ambiguous assignment.', 'Show the questions you asked, the success criteria you defined, and how you moved forward.'),
    ('Tell me about a time you were creative.', 'Describe the constraint, the unusual but practical approach, and evidence it worked.'),
    ('Tell me about a risk you took.', 'Explain the calculated risk, alternatives, mitigation, outcome, and what you learned.'),
    ('Tell me about a time you persuaded someone.', 'Describe their initial view, the tailored evidence you used, and the decision or result.'),
    ('Tell me about a time you had to say no.', 'Explain the priority conflict, how you communicated respectfully, and the alternative you offered.'),
    ('Tell me about a time you managed a stakeholder.', 'Show expectation setting, regular communication, handling concerns, and the project outcome.'),
    ('Tell me about a time you handled confidential information.', 'State how you followed policy, minimized access, protected information, and escalated uncertainty.'),
    ('Tell me about your proudest accomplishment.', 'Choose a relevant achievement, explain your direct contribution, and quantify the result.'),
    ('Tell me about a project you are proud of.', 'Use STAR and include technical or collaboration choices that demonstrate the role’s required skills.'),
    ('Tell me about a project that did not go as planned.', 'Be candid about the gap, recovery actions, stakeholder communication, and lasting lesson.'),
    ('Tell me about a time you had to make a tradeoff.', 'Explain the options, decision criteria, who you aligned with, and why the tradeoff was right then.'),
    ('Tell me about a time you improved quality.', 'Describe how you found the quality risk, changed the process, and measured fewer defects or better outcomes.'),
    ('Tell me about a time you managed up.', 'Show proactive communication of risks, context, options, and the support you enabled your manager to provide.'),
    ('How do you handle stress?', 'Give a concise real example of planning, boundaries, support, and maintaining effective work quality.'),
    ('What are your career goals?', 'Describe a realistic direction that this role advances, while emphasizing contribution and learning rather than title alone.'),
    ('Do you have questions for us?', 'Ask thoughtful questions about success measures, team challenges, collaboration, and growth; avoid saying no.'),
]
