"""100 JavaScript coding exercises for modern JavaScript in strict mode."""

from tricky_questions import build_coding_library


JAVASCRIPT_TRICKY_CASES = [
    ('Coercion in addition',
     'console.log(1 + "2" + 3);\nconsole.log(1 + 2 + "3");',
     '123, then 33 (both strings). Evaluation is left to right; a string operand switches + to concatenation.',
     'Sum the numeric values in [1, "2", 3] rather than concatenating.',
     'const total = [1, "2", 3].reduce((sum, x) => sum + Number(x), 0);',
     'Assert total === 6. Test ["0", 0] -> 0 and [] -> 0. Decide whether invalid numeric strings should be rejected rather than producing NaN.',
     'Replace the first expression with 1 + +"2" + 3.',
     '6, then 33. Unary + converts "2" to a number.'),
    ('NaN detection',
     'const value = Number("oops");\nconsole.log(value === NaN);\nconsole.log(Number.isNaN(value));',
     'false, then true. NaN never equals itself.',
     'Write isInvalidNumber(value) that detects NaN without coercing other types.',
     'const isInvalidNumber = value => Number.isNaN(value);',
     'Assert true for NaN and Number("oops"); false for "oops", undefined, and 0.',
     'Set value to the string "oops" without calling Number.',
     'false, then false. Number.isNaN does not coerce the string.'),
    ('Null object guard',
     'const value = null;\nif (typeof value === "object") {\n  console.log(value.name);\n}',
     'TypeError when reading name because typeof null is "object".',
     'Read name only for non-null objects, excluding arrays.',
     'if (value !== null && typeof value === "object" && !Array.isArray(value)) {\n  console.log(value.name);\n}',
     'Verify null, undefined, [], and "x" are skipped without throwing; {name: "Ada"} logs Ada.',
     'Set value to {}.',
     'undefined prints: the guard succeeds but name is absent.'),
    ('Loop callback capture',
     'const jobs = [];\nfor (var i = 0; i < 3; i++) jobs.push(() => i);\nconsole.log(jobs.map(fn => fn()).join(","));',
     '3,3,3. All callbacks share the function-scoped i.',
     'Capture one value per iteration.',
     'const jobs = [];\nfor (let i = 0; i < 3; i++) jobs.push(() => i);',
     'Assert jobs.map(fn => fn()).join(",") === "0,1,2". Call jobs[0]() again and expect 0.',
     'Change i < 3 to i < 1 in the original loop.',
     '1. The single closure reads i after the increment and failed loop condition.'),
    ('Temporal dead zone',
     'let x = 1;\n{\n  console.log(x);\n  let x = 2;\n}',
     'ReferenceError. The inner x shadows the outer x throughout the block but is not initialized yet.',
     'Print the inner value 2 without changing the outer x.',
     'let x = 1;\n{\n  let x = 2;\n  console.log(x);\n}',
     'Capture the block output and expect 2; after the block assert x === 1.',
     'Remove the inner declaration let x = 2.',
     '1. Lookup now reaches the outer binding.'),
    ('Lost method receiver',
     '"use strict";\nconst user = {name: "Ada", getName() { return this.name; }};\nconst get = user.getName;\nconsole.log(get());',
     'TypeError. The detached strict-mode call has this === undefined.',
     'Create a detached callback that retains user as its receiver.',
     'const get = user.getName.bind(user);\nconsole.log(get());',
     'Assert get() === "Ada"; change user.name to "Grace" and assert get() === "Grace". Verify get.call({name: "X"}) still returns "Grace".',
     'Replace get() with get.call({name: "Lin"}).',
     'Lin. call explicitly supplies the receiver.'),
    ('Arrow captures this',
     'const obj = {\n  n: 2,\n  make() { return () => this.n; }\n};\nconst fn = obj.make();\nconsole.log(fn.call({n: 9}));',
     '2. The arrow retains this from obj.make(); call cannot override it.',
     'Return a normal function so callers can choose this with call.',
     'const obj = {n: 2, make() { return function () { return this.n; }; }};',
     'const fn = obj.make(); assert fn.call({n: 9}) === 9 and fn.call({n: 0}) === 0.',
     'Set obj.n = 5 before calling the original fn.',
     '5. The arrow captures the object receiver, not a snapshot of its n property.'),
    ('Microtasks before timers',
     'console.log("A");\nsetTimeout(() => console.log("B"), 0);\nPromise.resolve().then(() => console.log("C"));\nconsole.log("D");',
     'A, D, C, B. Synchronous code completes, then the promise microtask, then the timer.',
     'Schedule B only after the promise callback has logged C.',
     'console.log("A");\nPromise.resolve().then(() => {\n  console.log("C");\n  setTimeout(() => console.log("B"), 0);\n});\nconsole.log("D");',
     'Collect log labels and wait for the timer; assert ["A", "D", "C", "B"]. Avoid asserting an exact elapsed time for a zero-delay timer.',
     'Inside the C callback, queue Promise.resolve().then(() => console.log("E")).',
     'A, D, C, E, B. The additional microtask runs before the timer.'),
    ('Missing promise return',
     'Promise.resolve(2)\n  .then(x => { x * 3; })\n  .then(console.log);',
     'undefined. The block-bodied callback has no return.',
     'Pass the multiplied value to the next handler.',
     'Promise.resolve(2).then(x => x * 3).then(console.log);',
     'Await the chain before its logging handler and assert the result is 6. Test initial values 0 -> 0 and -2 -> -6.',
     'Replace the callback with x => Promise.resolve(x * 3).',
     '6. The chain adopts the returned promise result.'),
    ('Async forEach',
     'async function run() {\n  const out = [];\n  [1, 2].forEach(async x => {\n    await Promise.resolve();\n    out.push(x);\n  });\n  console.log(out.length);\n}\nrun();',
     '0. forEach does not wait for its async callbacks.',
     'Wait for all asynchronous transformations and preserve input order.',
     'async function run() {\n  const out = await Promise.all([1, 2].map(async x => {\n    await Promise.resolve();\n    return x;\n  }));\n  console.log(out.length);\n}',
     'Expect length 2. Use transformations that finish in reverse order and assert Promise.all still returns [1, 2]. Empty input should produce [].',
     'Remove await Promise.resolve() from the original callback.',
     '2. Each async callback executes its push synchronously before returning its promise.'),
    ('Catching async failures',
     'async function run() {\n  try {\n    return Promise.reject(new Error("bad"));\n  } catch {\n    return "caught";\n  }\n}\nrun().then(console.log, e => console.log(e.message));',
     'bad. Returning a rejected promise bypasses the local catch; the caller handles the rejection.',
     'Handle the rejection in the local catch and return "caught".',
     'Change the try body to return await Promise.reject(new Error("bad"));',
     'Assert await run() === "caught". In a success variant using Promise.resolve("ok"), assert await run() === "ok".',
     'Replace return Promise.reject(...) with throw new Error("bad").',
     'caught. The synchronous throw is caught locally.'),
    ('Optional chaining boundary',
     'const user = null;\nconsole.log((user?.profile).name);',
     'TypeError. Parentheses end the optional chain; .name reads from undefined.',
     'Return undefined safely when either user or profile is nullish.',
     'console.log(user?.profile?.name);',
     'Test null, {}, and {profile: null} -> undefined; {profile: {name: "Ada"}} -> "Ada".',
     'Set user to {profile: {name: "Ada"}}.',
     'Ada. All accessed properties exist.'),
    ('Zero is a valid setting',
     'const config = {retries: 0};\nconsole.log(config.retries || 3);',
     '3. || treats zero as falsy.',
     'Default retries only for null or undefined.',
     'console.log(config.retries ?? 3);',
     'Test retries 0 -> 0, 2 -> 2, null -> 3, and missing -> 3.',
     'Set retries to -1 in the original code.',
     '-1. Negative numbers are truthy.'),
    ('Spread is shallow',
     'const a = {tags: ["a"]};\nconst b = {...a};\nb.tags.push("b");\nconsole.log(a.tags.join(","));',
     'a,b. Both objects share the tags array.',
     'Copy this object and its tags array so pushes on b do not affect a.',
     'const b = {...a, tags: [...a.tags]};',
     'After b.tags.push("b"), assert a.tags.join(",") === "a" and b.tags.join(",") === "a,b". Verify b.tags !== a.tags.',
     'Replace b.tags.push("b") with b.tags = ["b"].',
     'a. Replacing the copied object property does not mutate the original array.'),
    ('Array fill aliases',
     'const rows = Array(3).fill([]);\nrows[0].push(1);\nconsole.log(JSON.stringify(rows));',
     '[[1],[1],[1]]. fill stores the same array reference in every slot.',
     'Create independent row arrays.',
     'const rows = Array.from({length: 3}, () => []);\nrows[0].push(1);',
     'Assert JSON.stringify(rows) === "[[1],[],[]]" and rows[0] !== rows[1]. Test zero rows -> [].',
     'Replace rows[0].push(1) with rows[0] = [1].',
     '[[1],[],[]]. Only the first outer slot is replaced.'),
    ('Object identity in a Set',
     'const items = [{id: 1}, {id: 1}];\nconsole.log(new Set(items).size);',
     '2. Distinct objects remain distinct Set entries even when their fields match.',
     'Deduplicate by id, keeping the first object for each id.',
     'const seen = new Set();\nconst unique = items.filter(item => {\n  if (seen.has(item.id)) return false;\n  seen.add(item.id);\n  return true;\n});',
     'Assert unique.length === 1 and unique[0] === items[0]. Test ids [2, 1, 2] -> [2, 1], preserving first occurrence order; [] -> [].',
     'Set items to [obj, obj] where obj = {id: 1}.',
     '1. Both entries hold the same object reference.'),
    ('JSON data loss',
     'console.log(JSON.stringify({a: undefined, b: NaN}));\nconsole.log(JSON.stringify([undefined, NaN]));',
     '{"b":null}, then [null,null]. Undefined object fields disappear; undefined array elements and NaN become null.',
     'Encode undefined and NaN as explicit markers with a JSON replacer.',
     'const replacer = (key, value) => value === undefined ? "<undefined>" :\n  Number.isNaN(value) ? "<NaN>" : value;\nconsole.log(JSON.stringify({a: undefined, b: NaN}, replacer));',
     'Expect {"a":"<undefined>","b":"<NaN>"}. Test array markers, normal numbers, and null. These markers are display-only unless a collision-safe decoding scheme is also defined.',
     'Replace NaN in the object with 1n.',
     'The first stringify throws TypeError because BigInt has no default JSON serialization; the second line is not reached.'),
    ('parseInt as map callback',
     'console.log(JSON.stringify(["10", "10", "10"].map(parseInt)));',
     '[10,null,2]. map passes indices as parseInt radices: 0 -> 10, 1 -> NaN, 2 -> 2. JSON renders NaN as null.',
     'Parse every string in base 10.',
     'const values = ["10", "10", "10"].map(value => parseInt(value, 10));',
     'Assert values.join(",") === "10,10,10". Test ["08", "09"] -> [8, 9] and [] -> []. Document that parseInt("12px", 10) accepts the prefix 12.',
     'Replace map(parseInt) with map(Number).',
     '[10,10,10]. Number ignores the additional map callback arguments.'),
    ('Numeric sort',
     'const values = [2, 10, 1];\nconsole.log(values.sort().join(","));',
     '1,10,2. Default sort compares string representations.',
     'Sort numbers ascending without mutating values.',
     'const sorted = [...values].sort((a, b) => a - b);',
     'For a fresh [2, 10, 1], assert sorted.join(",") === "1,2,10" and values.join(",") === "2,10,1". Test negatives, duplicates, and empty input.',
     'Change sort() to sort((a, b) => b - a).',
     '10,2,1. The numeric comparator sorts descending.'),
    ('Empty reduce',
     'const values = [];\nconsole.log(values.reduce((sum, x) => sum + x));',
     'TypeError. There is no initial accumulator or first element.',
     'Return zero for empty input and the sum for numeric inputs.',
     'const total = values.reduce((sum, x) => sum + x, 0);',
     'Test [] -> 0, [5] -> 5, [1, -1] -> 0, and [1, 2, 3] -> 6.',
     'Set values to [5] in the original code.',
     '5. The sole element becomes the accumulator; the callback is never called.'),
    ('Destructuring null',
     'const {limit = 10} = {limit: null};\nconsole.log(limit);',
     'null. A destructuring default only replaces undefined.',
     'Apply a default for both null and undefined while retaining zero.',
     'const config = {limit: null};\nconst limit = config.limit ?? 10;',
     'Test null -> 10, absent -> 10, undefined -> 10, 0 -> 0, and 5 -> 5.',
     'Replace {limit: null} with {}.',
     '10. The extracted property is undefined, so the destructuring default applies.'),
    ('Inherited properties',
     'const obj = Object.create({role: "admin"});\nobj.name = "Ada";\nconsole.log("role" in obj);\nconsole.log(Object.keys(obj).join(","));',
     'true, then name. in searches prototypes, whereas Object.keys returns own enumerable keys.',
     'Check whether role belongs directly to obj.',
     'const hasOwnRole = Object.prototype.hasOwnProperty.call(obj, "role");',
     'Expect false for the inherited role, then true after obj.role = "editor". Verify the check works on Object.create(null).',
     'Add obj.role = "editor" before both logs.',
     'true, then name,role. The new own property follows name in insertion order.'),
    ('Sparse array mapping',
     'const values = new Array(3).map((_, i) => i);\nconsole.log(values.length);\nconsole.log(Object.keys(values).length);',
     '3, then 0. map skips empty slots, preserving holes.',
     'Construct a dense array [0, 1, 2].',
     'const values = Array.from({length: 3}, (_, i) => i);',
     'Assert values.join(",") === "0,1,2" and Object.keys(values).length === 3. Test length 0 -> [].',
     'Insert .fill(undefined) before .map in the original code.',
     '3, then 3. Explicit undefined entries are visited by map.'),
    ('Splice return value',
     'const values = [1, 2, 3, 4];\nconst result = values.splice(1, 2);\nconsole.log(values.join(","));\nconsole.log(result.join(","));',
     '1,4, then 2,3. splice mutates values and returns the removed elements.',
     'Extract the middle two elements without changing values.',
     'const result = values.slice(1, 3);',
     'For fresh [1, 2, 3, 4], assert result.join(",") === "2,3" and values.join(",") === "1,2,3,4". Empty input returns [].',
     'Replace splice(1, 2) with splice(1, 0, 9).',
     '1,9,2,3,4, then an empty line. Insertion removes no elements, so result is [].'),
    ('Promise result ordering',
     'const slow = new Promise(resolve => setTimeout(() => resolve("slow"), 10));\nconst fast = Promise.resolve("fast");\nPromise.all([slow, fast]).then(values => console.log(values.join(",")));',
     'slow,fast. Promise.all preserves input order regardless of completion order.',
     'Get the first settled result from these two promises.',
     'Promise.race([slow, fast]).then(console.log);',
     'Expect "fast" for this setup. Use controlled promises to verify that the first rejection rejects race and the first fulfillment fulfills it; await each assertion.',
     'Reverse the input array passed to Promise.all.',
     'fast,slow. The output follows the new input order.'),
]

JAVASCRIPT_TRICKY_QUESTIONS = build_coding_library('JavaScript', JAVASCRIPT_TRICKY_CASES)
