"""100 Python coding exercises: output tracing, fixes, tests, and edge cases."""

from tricky_questions import build_coding_library


PYTHON_TRICKY_CASES = [
    ('Shared defaults',
     'def add(x, items=[]):\n    items.append(x)\n    return items\nprint(add(1))\nprint(add(2))',
     '[1], then [1, 2]. Both calls mutate the same default list.',
     'Make omitted lists independent while still mutating an explicitly supplied list.',
     'def add(x, items=None):\n    if items is None:\n        items = []\n    items.append(x)\n    return items',
     'assert add(1) == [1]\nassert add(2) == [2]\nitems = []\nassert add(3, items) is items\nassert items == [3]',
     'Replace the second call with add(2, []). What prints?',
     '[1], then [2]. The second call supplies a separate list.'),
    ('Loop closures',
     'funcs = [lambda: i for i in range(3)]\nprint([f() for f in funcs])',
     '[2, 2, 2]. All closures read the same final loop binding.',
     'Capture each iteration value so the result is [0, 1, 2].',
     'funcs = [lambda i=i: i for i in range(3)]',
     'assert [f() for f in funcs] == [0, 1, 2]\nassert funcs[0]() == 0\nassert funcs[2]() == 2',
     'Change range(3) to range(0). What prints?',
     '[]. No functions are created.'),
    ('Aliased matrix rows',
     'rows = [[0] * 2] * 3\nrows[0][1] = 9\nprint(rows)',
     '[[0, 9], [0, 9], [0, 9]]. All three entries refer to one row.',
     'Allocate independent rows.',
     'rows = [[0] * 2 for _ in range(3)]\nrows[0][1] = 9',
     'assert rows == [[0, 9], [0, 0], [0, 0]]\nassert rows[0] is not rows[1]',
     'Replace rows[0][1] = 9 with rows[0] = [9, 9].',
     '[[9, 9], [0, 0], [0, 0]]. Replacing an outer slot does not mutate the shared row.'),
    ('Nested shallow copy',
     'a = {"tags": ["a"]}\nb = a.copy()\nb["tags"].append("b")\nprint(a["tags"])',
     "['a', 'b']. The copied dictionary shares the nested list.",
     'Copy this data so nested mutations do not affect a.',
     'from copy import deepcopy\nb = deepcopy(a)',
     'Start with a = {"tags": ["a"]}; copy it, append "b" to b["tags"], then assert a["tags"] == ["a"] and b["tags"] == ["a", "b"].',
     'Replace append with b["tags"] = ["b"].',
     "['a']. Rebinding the copied dictionary entry does not change a."),
    ('Exhausted generator',
     'values = (x * x for x in range(3))\nprint(sum(values))\nprint(list(values))',
     '5, then []. sum consumes the generator.',
     'Allow summing and then listing all values.',
     'values = [x * x for x in range(3)]\nprint(sum(values))\nprint(list(values))',
     'For range(3), expect 5 and [0, 1, 4]. For range(0), expect 0 and []. Repeat list(values) and verify the same contents.',
     'Insert print(next(values)) before sum.',
     '0, then 5, then []. The first square is consumed before sum.'),
    ('Local assignment',
     'count = 10\ndef bump():\n    count += 1\n    return count\nprint(bump())',
     'UnboundLocalError. Assignment makes count local, but its old local value does not exist.',
     'Rewrite bump as a pure function receiving the current count.',
     'def bump(count):\n    return count + 1\nprint(bump(count))',
     'assert bump(10) == 11\nassert bump(-1) == 0\nassert count == 10',
     'Insert global count as the first line inside bump.',
     '11 prints and the module-level count becomes 11.'),
    ('Counter closure',
     'def counter():\n    n = 0\n    def inc():\n        n += 1\n        return n\n    return inc\nprint(counter()())',
     'UnboundLocalError inside inc because n is treated as local.',
     'Make each returned counter retain independent state.',
     'Add nonlocal n before n += 1 inside inc.',
     'a, b = counter(), counter()\nassert a() == 1\nassert a() == 2\nassert b() == 1',
     'Replace n += 1 with return n + 1, leaving the following return unreachable.',
     '1 prints. Repeated calls also return 1 because n is never updated.'),
    ('Equal dictionary keys',
     'd = {True: "yes", 1: "one", 1.0: "float"}\nprint(len(d))\nprint(d[True])',
     '1, then float. These keys compare equal and have equal hashes, so later values overwrite earlier ones.',
     'Keep bool, int, and float keys distinct using a key-normalization function.',
     'def key(value):\n    return (type(value), value)\nd = {key(True): "yes", key(1): "one", key(1.0): "float"}',
     'assert len(d) == 3\nassert d[key(True)] == "yes"\nassert d[key(1)] == "one"\nassert d[key(1.0)] == "float"',
     'Replace the key 1.0 with the string "1".',
     '2, then one. True and 1 still collide; the string is distinct.'),
    ('Unhashable coordinates',
     'seen = set()\nseen.add([1, 2])\nprint(len(seen))',
     'TypeError at add: lists are unhashable. print is not reached.',
     'Store numeric coordinate pairs in a set and deduplicate equal pairs.',
     'seen = set()\nseen.add((1, 2))',
     'seen.add((1, 2))\nassert len(seen) == 1\nseen.add((2, 1))\nassert len(seen) == 2',
     'Use ([1], 2) instead of [1, 2].',
     'TypeError still occurs: a tuple containing an unhashable list is also unhashable.'),
    ('In-place sorting',
     'values = [3, 1, 2]\nresult = values.sort()\nprint(result)\nprint(values)',
     'None, then [1, 2, 3]. sort mutates values and returns None.',
     'Return a sorted list without changing values.',
     'result = sorted(values)',
     'With values = [3, 1, 2], assert result == [1, 2, 3] and values == [3, 1, 2]. Also test [] and [2, 2].',
     'Change sort() to sort(reverse=True).',
     'None, then [3, 2, 1]. The return value remains None.'),
    ('Removing during iteration',
     'values = [2, 4, 6, 7]\nfor x in values:\n    if x % 2 == 0:\n        values.remove(x)\nprint(values)',
     '[4, 7]. Removing 2 shifts 4 behind the next iterator position, so 4 is skipped.',
     'Remove all even numbers while preserving the original list object.',
     'values[:] = [x for x in values if x % 2 != 0]',
     'Keep alias = values before the change; assert values == [7] and alias is values. Test all-even input -> [] and empty input -> [].',
     'Iterate over values[:] instead of values.',
     '[7]. Iteration uses a separate snapshot while removals affect the original.'),
    ('Falsy defaults',
     'def limit(value):\n    return value or 10\nprint(limit(0))\nprint(limit(None))',
     '10, then 10. or replaces both zero and None.',
     'Default only when the argument is None.',
     'def limit(value):\n    return 10 if value is None else value',
     'assert limit(0) == 0\nassert limit(None) == 10\nassert limit(5) == 5',
     'Replace the first call with limit(-1).',
     '-1, then 10. A negative integer is truthy.'),
    ('Finally overrides return',
     'def value():\n    try:\n        return 1\n    finally:\n        return 2\nprint(value())',
     '2. The finally return replaces the pending try return.',
     'Keep a cleanup step without overriding the return from try.',
     'def value():\n    try:\n        return 1\n    finally:\n        print("cleanup")',
     'Capture stdout and assert it is "cleanup\\n"; assert value() returns 1. In a variant whose try raises ValueError, verify cleanup runs and ValueError propagates.',
     'Replace return 1 with raise ValueError("bad").',
     '2 still prints. The return in finally suppresses the exception.'),
    ('Tuple augmented assignment',
     'pair = ([1], 2)\ntry:\n    pair[0] += [3]\nexcept TypeError:\n    print(pair)',
     '([1, 3], 2). The list mutates before assignment back to the immutable tuple fails.',
     'Append 3 to the nested list without raising an exception.',
     'pair[0].extend([3])',
     'pair = ([1], 2); pair[0].extend([3]); assert pair == ([1, 3], 2). Verify the original nested list object is retained.',
     'Replace += with pair[0] = pair[0] + [3].',
     '([1], 2). Concatenation creates a new list, and the failed tuple assignment leaves the original intact.'),
    ('Shared class state',
     'class Bag:\n    items = []\na, b = Bag(), Bag()\na.items.append("x")\nprint(b.items)',
     "['x']. Both instances read the class-level list.",
     'Give every Bag its own items list.',
     'class Bag:\n    def __init__(self):\n        self.items = []',
     'a, b = Bag(), Bag()\na.items.append("x")\nassert b.items == []\nassert a.items is not b.items',
     'Replace a.items.append("x") with a.items = ["x"].',
     '[]. Assignment creates an instance attribute on a; b still sees the class list.'),
    ('Annotations do not validate',
     'def double(x: int) -> int:\n    return x * 2\nprint(double("3"))',
     '33. The string is repeated; annotations do not enforce runtime types.',
     'Reject all inputs except exact int values, including rejecting bool.',
     'def double(x: int) -> int:\n    if type(x) is not int:\n        raise TypeError("expected int")\n    return x * 2',
     'assert double(3) == 6 and double(0) == 0. Verify "3", True, and 3.0 each raise TypeError.',
     'Replace "3" with True in the original call.',
     '2. bool participates in integer arithmetic.'),
    ('Negative floor division',
     'print(-7 // 3)\nprint(-7 % 3)',
     '-3, then 2. Floor division rounds down, and -7 == (-3) * 3 + 2.',
     'Implement integer division truncated toward zero for arbitrary-size integers without converting to float.',
     'def trunc_div(a, b):\n    q = abs(a) // abs(b)\n    return -q if (a < 0) != (b < 0) else q',
     'assert trunc_div(-7, 3) == -2\nassert trunc_div(7, -3) == -2\nassert trunc_div(-7, -3) == 2\nassert trunc_div(10**100, 1) == 10**100\nAlso verify a zero divisor raises ZeroDivisionError.',
     'Change both divisors from 3 to -3.',
     '2, then -1. -7 == 2 * (-3) + (-1).'),
    ('Floating-point comparison',
     'print(0.1 + 0.2 == 0.3)',
     'False. Binary floating-point rounding prevents exact equality here.',
     'Compare these computed values using a numerical tolerance.',
     'import math\nprint(math.isclose(0.1 + 0.2, 0.3, rel_tol=1e-9, abs_tol=1e-12))',
     'Verify 0.1 + 0.2 versus 0.3 is close, 0 versus 1e-13 is close with abs_tol=1e-12, and 0.3 versus 0.4 is not close.',
     'Use 0.5 + 0.25 == 0.75 instead.',
     'True. These fractions are exactly representable in binary.'),
    ('Zip truncation',
     'names = ["a", "b"]\nscores = [10]\nprint(dict(zip(names, scores)))',
     "{'a': 10}. zip stops at the shorter input.",
     'Reject mismatched list lengths before constructing the dictionary.',
     'if len(names) != len(scores):\n    raise ValueError("length mismatch")\nresult = dict(zip(names, scores))',
     'Two names and one score must raise ValueError. Equal-length inputs produce all pairs. Two empty lists produce {}.',
     'Change scores to [10, 20, 30].',
     "{'a': 10, 'b': 20}. The third score is ignored."),
    ('Late generator lookup',
     'factor = 2\nvalues = (x * factor for x in range(3))\nfactor = 10\nprint(list(values))',
     '[0, 10, 20]. Multiplication reads factor during iteration.',
     'Keep evaluation lazy but capture the factor when creating the generator.',
     'def scaled(factor):\n    return (x * factor for x in range(3))\nvalues = scaled(factor)',
     'Create values = scaled(2), then change the outer factor to 10 and assert list(values) == [0, 2, 4]. Also assert list(scaled(0)) == [0, 0, 0].',
     'Replace the generator expression with a list comprehension.',
     '[0, 2, 4]. The list is fully computed before factor changes.'),
    ('Identity versus equality',
     'a = [1, 2]\nb = [1, 2]\nprint(a == b, a is b)',
     'True False. Contents match, but these are distinct lists.',
     'Implement same_values(a, b) for list-content comparison.',
     'def same_values(a, b):\n    return a == b',
     'assert same_values([1], [1])\nassert not same_values([1], [2])\nassert same_values([], [])',
     'Replace b = [1, 2] with b = a.',
     'True True. Both names refer to the same list.'),
    ('Boolean expression bug',
     'def allowed(role):\n    return role == "admin" or "editor"\nprint(allowed("guest"))',
     'editor. The second operand is returned as a truthy string, so a guest passes an if check.',
     'Return a boolean allowing only admin and editor.',
     'def allowed(role):\n    return role in ("admin", "editor")',
     'assert allowed("admin") is True\nassert allowed("editor") is True\nassert allowed("guest") is False\nassert allowed("") is False',
     'Call the original function with "admin".',
     'True. or short-circuits on the successful comparison.'),
    ('Exception target cleanup',
     'error = "before"\ntry:\n    1 / 0\nexcept ZeroDivisionError as error:\n    pass\nprint(error)',
     'NameError. Python clears the exception target after the handler, including the previous binding.',
     'Store a printable error message for later use.',
     'message = None\ntry:\n    1 / 0\nexcept ZeroDivisionError as error:\n    message = str(error)\nprint(message)',
     'Verify message is "division by zero" after failure. In a no-error variant, verify message remains None and is defined.',
     'Rename the except target to exc, keeping print(error).',
     'before. Only exc is cleared; the original error binding survives.'),
    ('Overlapping substring search',
     'print("aaaa".count("aa"))',
     '2. str.count counts non-overlapping matches.',
     'Count overlapping occurrences of a nonempty substring; reject an empty needle.',
     'def overlaps(text, needle):\n    if not needle:\n        raise ValueError("empty needle")\n    return sum(text.startswith(needle, i) for i in range(len(text)))',
     'assert overlaps("aaaa", "aa") == 3\nassert overlaps("", "a") == 0\nassert overlaps("ab", "abc") == 0\nVerify an empty needle raises ValueError.',
     'Change the original text to "aaaaa".',
     '2. A trailing single a does not make another non-overlapping pair.'),
    ('Coroutine execution',
     'import asyncio\nasync def work():\n    print("work")\n    return 7\nasync def main():\n    job = work()\n    print("created")\n    print(await job)\nasyncio.run(main())',
     'created, work, 7 on separate lines. Calling work creates a coroutine; await runs it.',
     'Run work twice and collect both results with asyncio.gather.',
     'async def main():\n    results = await asyncio.gather(work(), work())\n    print(results)\nasyncio.run(main())',
     'Capture stdout: work must appear twice, followed by [7, 7]. Verify neither result is a coroutine object.',
     'Add print(await job) a second time after the first await.',
     'After created, work, and 7, RuntimeError occurs because an already awaited coroutine cannot be reused.'),
]

PYTHON_TRICKY_QUESTIONS = build_coding_library('Python 3', PYTHON_TRICKY_CASES)
