"""A curated set of common Python coding-interview prompts and short answers."""

PYTHON_QUESTIONS = [
    ('Reverse a string.', 'Use slicing: `text[::-1]`. For Unicode grapheme clusters, use a library designed for graphemes.'),
    ('Check whether a string is a palindrome.', 'Normalize if needed, then compare `text == text[::-1]`.'),
    ('Find the first non-repeating character.', 'Count characters with `collections.Counter`, then scan the original string for the first count of one.'),
    ('Count character frequency in a string.', 'Use `collections.Counter(text)` or a dictionary updated in one pass.'),
    ('Remove duplicate characters while preserving order.', 'Use `"".join(dict.fromkeys(text))`; dictionaries preserve insertion order.'),
    ('Check whether two strings are anagrams.', 'Compare `Counter(a)` and `Counter(b)` after applying the same normalization.'),
    ('Find the longest word in a sentence.', 'Use `max(sentence.split(), key=len, default="")`.'),
    ('Capitalize the first letter of every word.', 'Use `text.title()` for simple text, or split and capitalize each word for custom rules.'),
    ('Find all duplicate words in text.', 'Count normalized words with `Counter`; keep keys whose count is greater than one.'),
    ('Compress repeated characters such as aaabb.', 'Scan runs and emit the character plus its count, producing `a3b2`.'),
    ('Reverse the words in a sentence.', 'Use `" ".join(sentence.split()[::-1])` to also normalize whitespace.'),
    ('Find the common prefix of strings.', 'Compare characters column by column, or use `os.path.commonprefix` for a simple prefix.'),
    ('Implement FizzBuzz.', 'Loop from 1 to n; test divisibility by 15, then 3, then 5 before printing the number.'),
    ('Find a missing number from 0 through n.', 'Use `n * (n + 1) // 2 - sum(numbers)` when exactly one value is missing.'),
    ('Find duplicates in a list.', 'Track a `seen` set and add a value to duplicates when it is already present.'),
    ('Remove duplicates from a list while preserving order.', 'Use `list(dict.fromkeys(values))` when list items are hashable.'),
    ('Find the second-largest distinct number.', 'Track the largest and second-largest in one pass, or use `sorted(set(values))[-2]` after validation.'),
    ('Find the largest and smallest values in a list.', 'Use `max(values)` and `min(values)`; handle an empty list first.'),
    ('Move all zeros to the end of a list.', 'Build non-zero values, then append the required number of zeros.'),
    ('Merge two sorted lists.', 'Advance two indexes, repeatedly taking the smaller item, then append either remainder.'),
    ('Find the intersection of two lists.', 'For unique items use `set(a) & set(b)`; use `Counter` when duplicate counts matter.'),
    ('Find the union of two lists.', 'Use `set(a) | set(b)` for unique unordered values, or a seen set to preserve order.'),
    ('Rotate a list right by k positions.', 'Reduce `k` with modulo length, then return `items[-k:] + items[:-k]`.'),
    ('Flatten a one-level nested list.', 'Use `[item for group in groups for item in group]`.'),
    ('Flatten an arbitrarily nested list.', 'Write a recursive generator that yields scalars and recursively yields from nested lists.'),
    ('Split a list into chunks.', 'Use `[items[i:i+n] for i in range(0, len(items), n)]` after validating a positive chunk size.'),
    ('Find pairs that sum to a target.', 'Store seen values in a set; for each value check whether `target - value` was seen.'),
    ('Solve Two Sum and return indexes.', 'Store each value’s index in a dictionary; look up the complement before inserting the current item.'),
    ('Find the majority element.', 'Use Boyer–Moore voting, then verify the candidate if a majority is not guaranteed.'),
    ('Find the kth largest element.', 'Use `heapq.nlargest(k, values)[-1]`, or quickselect for average linear time.'),
    ('Sort a list of dictionaries by a key.', 'Use `sorted(rows, key=lambda row: row["score"])`.'),
    ('Group dictionaries by a shared key.', 'Use `defaultdict(list)` and append each row under `row["key"]`.'),
    ('Sort a dictionary by value.', 'Use `sorted(data.items(), key=lambda pair: pair[1])`.'),
    ('Invert a dictionary.', 'Use `{value: key for key, value in data.items()}` only when values are unique and hashable.'),
    ('Safely merge two dictionaries.', 'Use `{**left, **right}`; right-side values overwrite matching left-side keys.'),
    ('Explain shallow copy versus deep copy.', 'A shallow copy shares nested objects; `copy.deepcopy` recursively copies nested objects.'),
    ('What is the difference between is and ==?', '`==` compares values; `is` compares object identity. Use `is None` for None checks.'),
    ('What is mutable and immutable in Python?', 'Lists, dicts, and sets are mutable; strings, tuples, ints, and frozensets are immutable.'),
    ('List versus tuple: when do you use each?', 'Use lists for changing sequences and tuples for fixed records or hashable immutable sequences.'),
    ('Set versus list: when do you use each?', 'Use a set for fast membership and uniqueness; use a list when order and duplicates matter.'),
    ('What is a dictionary comprehension?', 'It is concise dictionary construction: `{key: transform(value) for key, value in items}`.'),
    ('What is a list comprehension?', 'It creates a list from an iterable, optionally filtering: `[f(x) for x in xs if keep(x)]`.'),
    ('What is a generator expression?', 'It is a lazy iterable: `(f(x) for x in xs)`, useful when you do not need all values at once.'),
    ('Write a generator for Fibonacci numbers.', 'Keep `a, b = 0, 1`; repeatedly `yield a` then assign `a, b = b, a + b`.'),
    ('Explain yield versus return.', '`return` finishes a function; `yield` pauses it and makes the function produce an iterator.'),
    ('What does iter() and next() do?', '`iter(obj)` gets an iterator; `next(iterator)` retrieves the next value or raises StopIteration.'),
    ('What is a decorator?', 'A decorator takes a callable and returns a callable, often adding behavior around a function call.'),
    ('Write a timing decorator.', 'Wrap the function, record time with `perf_counter`, call it, then report elapsed time; use `functools.wraps`.'),
    ('What is a closure?', 'A closure is a function that remembers variables from its enclosing scope after that scope exits.'),
    ('What is a lambda expression?', 'It is a small anonymous expression function, best for short callbacks such as sort keys.'),
    ('What are *args and **kwargs?', '`*args` collects positional arguments into a tuple; `**kwargs` collects keyword arguments into a dictionary.'),
    ('Why avoid mutable default arguments?', 'Defaults are created once, so use `None` and create a new list or dict inside the function.'),
    ('What is LEGB scope?', 'Python resolves names in Local, Enclosing, Global, then Built-in scope.'),
    ('What do global and nonlocal do?', '`global` rebinds a module variable; `nonlocal` rebinds a variable in the nearest enclosing function scope.'),
    ('Explain exceptions: try, except, else, finally.', '`try` runs risky code; `except` handles errors; `else` runs on success; `finally` always runs.'),
    ('Create a custom exception.', 'Subclass `Exception`, for example `class ValidationError(Exception): pass`.'),
    ('What is a context manager?', 'It guarantees setup and cleanup around `with`, such as opening and closing a file.'),
    ('Write a context manager with contextlib.', 'Decorate a generator with `@contextmanager`, yield the resource, and clean up in `finally`.'),
    ('Explain __name__ == "__main__".', 'It runs code only when the file is executed directly, not when imported.'),
    ('What are dunder methods?', 'Special methods such as `__init__`, `__len__`, and `__repr__` define object behavior with Python syntax.'),
    ('What is __repr__ versus __str__?', '`__repr__` is an unambiguous developer representation; `__str__` is a readable user representation.'),
    ('What is a dataclass?', 'A `@dataclass` generates common methods like `__init__` and `__repr__` for data-focused classes.'),
    ('What is inheritance?', 'A child class reuses and extends a parent class; favor composition when a has-a relationship fits better.'),
    ('What is method overriding?', 'A subclass defines a method with the same name to change inherited behavior.'),
    ('What does super() do?', 'It calls the next implementation in the method resolution order, commonly a parent method.'),
    ('What is method resolution order?', 'MRO is the order Python searches base classes, visible with `Class.mro()`.'),
    ('What is an abstract base class?', 'An ABC defines an interface and can require subclasses to implement methods with `@abstractmethod`.'),
    ('What is a property?', '`@property` exposes controlled attribute access while keeping method logic behind attribute syntax.'),
    ('What is a classmethod?', 'It receives the class as `cls`; use it for alternate constructors or class-wide behavior.'),
    ('What is a staticmethod?', 'It receives neither instance nor class automatically; use it for related utility logic.'),
    ('What is a namedtuple?', 'It is a lightweight tuple subclass with named fields; a frozen dataclass is often a modern alternative.'),
    ('What is enumerate() useful for?', 'It yields index-value pairs while iterating: `for index, value in enumerate(values):`.'),
    ('What is zip() useful for?', 'It iterates over multiple iterables in parallel; use `strict=True` when equal lengths are required.'),
    ('What does map() do?', 'It lazily applies a function to each item; a comprehension is often clearer for simple transformations.'),
    ('What does filter() do?', 'It lazily keeps items for which a predicate is truthy; a comprehension is often clearer.'),
    ('What is functools.lru_cache?', 'It memoizes recent function calls, ideal for pure functions with repeated arguments.'),
    ('How do you check if a key exists in a dictionary?', 'Use `if key in data:` rather than catching KeyError for a normal membership check.'),
    ('How do you safely read a possibly missing dictionary key?', 'Use `data.get(key, default)` or `defaultdict` when a missing value should be created.'),
    ('What is defaultdict?', 'It is a dictionary that creates a default value for missing keys, such as `defaultdict(list)`.'),
    ('What is Counter?', 'It is a dictionary subclass specialized for counting hashable items.'),
    ('What is deque?', 'A `collections.deque` supports efficient appends and pops from both ends.'),
    ('Implement a stack.', 'Use a list: `append` pushes and `pop` removes the top; check for empty before popping.'),
    ('Implement a queue.', 'Use `collections.deque`: `append` enqueues and `popleft` dequeues in O(1) time.'),
    ('Check balanced parentheses.', 'Push opening brackets to a stack; pop and validate when a closing bracket appears.'),
    ('Reverse a linked list.', 'Iterate while redirecting each node’s next pointer to the previous node.'),
    ('Detect a cycle in a linked list.', 'Use Floyd’s slow and fast pointers; if they meet, the list has a cycle.'),
    ('Binary-search a sorted list.', 'Repeatedly compare the target to the middle element and discard half the search range.'),
    ('What is the time complexity of list membership?', 'It is O(n) because a list may scan values; set and dict membership are average O(1).'),
    ('What is the time complexity of dictionary lookup?', 'Average O(1), though collisions and resizing affect the constant factors.'),
    ('What is the time complexity of sorting?', 'Python’s Timsort is O(n log n) worst case and can be near O(n) on partially ordered data.'),
    ('How does Python memory management work?', 'CPython primarily uses reference counting plus a cyclic garbage collector for reference cycles.'),
    ('What is the GIL?', 'In CPython, the Global Interpreter Lock lets one thread execute Python bytecode at a time.'),
    ('Threads versus processes?', 'Threads share memory and suit I/O; processes use separate memory and can use multiple CPU cores.'),
    ('What is async and await?', 'They define cooperative asynchronous code; awaiting yields control while an I/O operation is pending.'),
    ('How do you read a large file efficiently?', 'Iterate over the file object line by line instead of calling `readlines()`.'),
    ('How do you parse JSON?', 'Use `json.loads` for a string and `json.load` for a file object; validate untrusted data.'),
    ('How do you make an HTTP request?', 'Use a client such as `requests` or `httpx`, set timeouts, check status, and handle failures.'),
    ('What is a virtual environment?', 'It isolates a project’s Python packages from other projects and the system installation.'),
    ('How do you test Python code?', 'Use pytest or unittest; test normal cases, edge cases, and failures in small isolated tests.'),
    ('What is type hinting?', 'Annotations such as `def add(a: int, b: int) -> int` document expected types and support static checking.'),
]
