"""Common React interview prompts with concise answers."""

REACT_QUESTIONS = [
    ('What is React?', 'A JavaScript library for building component-based user interfaces.'),
    ('What is a component?', 'A reusable UI unit that accepts inputs and returns React elements.'),
    ('Function versus class components?', 'Function components use hooks and are the modern default; class components use lifecycle methods.'),
    ('What is JSX?', 'A syntax extension that lets you describe UI with HTML-like markup inside JavaScript.'),
    ('Does JSX run in the browser directly?', 'Usually no; a build tool transforms JSX into JavaScript calls.'),
    ('What are props?', 'Read-only inputs passed from a parent component to a child component.'),
    ('What is state?', 'Component-owned data that can change over time and trigger a re-render.'),
    ('Props versus state?', 'Props are external and read-only; state is owned and updated by the component.'),
    ('What causes a React re-render?', 'A state update, new props, context change, or parent render can cause one.'),
    ('What is the virtual DOM?', 'An in-memory representation React compares to efficiently update the browser DOM.'),
    ('What is reconciliation?', 'React’s process for comparing old and new element trees and applying necessary DOM updates.'),
    ('Why are keys needed in lists?', 'Keys give sibling items stable identity during reconciliation.'),
    ('Why should list indexes rarely be keys?', 'Reordering or inserting can attach state to the wrong item.'),
    ('What is a fragment?', 'A way to group elements without adding an extra DOM node, using `<>...</>`.'),
    ('What is conditional rendering?', 'Showing different UI based on a condition with if statements, ternaries, or logical operators.'),
    ('What is event handling in React?', 'Passing callback functions such as `onClick={handleClick}` to elements.'),
    ('Why not call an event handler during render?', '`onClick={handleClick()}` runs immediately; pass the function reference instead.'),
    ('What is a controlled input?', 'An input whose value is driven by React state and updated through an onChange handler.'),
    ('What is an uncontrolled input?', 'An input that keeps its value in the DOM, commonly accessed through a ref.'),
    ('What is lifting state up?', 'Moving shared state to the closest common parent so children receive consistent props.'),
    ('What is prop drilling?', 'Passing props through components that do not use them just to reach a deep child.'),
    ('What is the Context API?', 'A way to share values through a subtree without manually passing props at every level.'),
    ('When should you avoid Context?', 'For frequently changing or complex state where it would re-render too many consumers.'),
    ('What is useState?', 'A hook that adds state to a function component.'),
    ('How should state be updated from prior state?', 'Use the updater form: `setCount(previous => previous + 1)`.'),
    ('Why should state not be mutated directly?', 'React relies on new references to detect changes and schedule updates predictably.'),
    ('How do you update an object in state?', 'Create a new object, for example `setUser({...user, name: value})`.'),
    ('How do you update an array in state?', 'Use immutable methods such as map, filter, slice, or spread.'),
    ('What is useEffect?', 'A hook for synchronizing a component with an external system after rendering.'),
    ('What is the useEffect dependency array?', 'It tells React which reactive values should cause the effect to run again.'),
    ('What does an empty dependency array mean?', 'The effect runs after initial mount; development Strict Mode may run setup twice to reveal bugs.'),
    ('What is effect cleanup?', 'A function returned from an effect that unsubscribes, clears timers, or cancels work.'),
    ('Why can useEffect create an infinite loop?', 'Updating state in an effect that depends on a value changed by that update repeats it.'),
    ('When should you not use useEffect?', 'Do not use it for values that can be calculated during rendering from props or state.'),
    ('What is useRef?', 'A hook for a mutable value or DOM node that persists across renders without causing re-renders.'),
    ('What is useMemo?', 'A hook that memoizes an expensive calculated value until its dependencies change.'),
    ('What is useCallback?', 'A hook that memoizes a function reference until dependencies change.'),
    ('useMemo versus useCallback?', 'useMemo caches a value; useCallback caches a function.'),
    ('When is memoization harmful?', 'It adds complexity and overhead when renders or calculations are already cheap.'),
    ('What is React.memo?', 'A higher-order component that can skip a child render when its props are unchanged.'),
    ('What is a custom hook?', 'A function beginning with `use` that shares stateful logic between components.'),
    ('What are the Rules of Hooks?', 'Call hooks only at the top level of React functions and only from components or custom hooks.'),
    ('What is useReducer?', 'A hook for managing state transitions with a reducer function and dispatched actions.'),
    ('When useReducer versus useState?', 'Use useReducer when state logic has related transitions or becomes easier to test as actions.'),
    ('What is Strict Mode?', 'A development tool that highlights unsafe patterns and intentionally rechecks some behavior.'),
    ('What is a portal?', 'A way to render children into a different DOM node while retaining React parent relationships.'),
    ('What is an error boundary?', 'A component that catches rendering errors below it and shows fallback UI; it is class-based today.'),
    ('What is Suspense?', 'A boundary that displays fallback UI while a lazy component or supported resource is not ready.'),
    ('What is React.lazy?', 'It code-splits a component by loading it dynamically with `import()`.'),
    ('What is code splitting?', 'Splitting JavaScript into smaller chunks loaded only when needed.'),
    ('What is hydration?', 'Attaching React behavior to HTML that was rendered on the server.'),
    ('CSR versus SSR?', 'Client-side rendering builds UI in the browser; server-side rendering sends initial HTML from a server.'),
    ('What is static site generation?', 'Rendering pages at build time and serving the generated HTML.'),
    ('What is Next.js?', 'A React framework that provides routing, rendering strategies, data loading, and production tooling.'),
    ('What is a single-page application?', 'An app that updates views client-side without full document navigation for most routes.'),
    ('What is client-side routing?', 'Changing UI based on the URL in the browser, often using React Router.'),
    ('What is React Router?', 'A common library for declaring routes and rendering components based on location.'),
    ('What is a higher-order component?', 'A function that takes a component and returns an enhanced component.'),
    ('What is render props?', 'A pattern where a component receives a function prop to decide what UI to render.'),
    ('What is composition in React?', 'Combining small components and children props instead of relying heavily on inheritance.'),
    ('How do you pass children?', 'Nest JSX inside a component and read it from the `children` prop.'),
    ('What are synthetic events?', 'React’s cross-browser event wrapper; modern React event behavior closely follows native events.'),
    ('What is event bubbling?', 'An event travels from its target to ancestors; use `stopPropagation` only when needed.'),
    ('What is batching?', 'React groups multiple state updates to reduce unnecessary re-renders.'),
    ('What are state update queues?', 'React queues updates and processes them during the next render rather than changing state immediately.'),
    ('Why can console.log show old state?', 'The current event handler closes over the state from the render where it was created.'),
    ('What is a stale closure?', 'A callback or effect uses older captured values because dependencies or update patterns are wrong.'),
    ('How do you fetch data in React?', 'Fetch in an effect or use a data library; handle loading, error, cancellation, and stale results.'),
    ('How do you avoid a fetch race condition?', 'Abort stale requests or ignore results that no longer match the current request.'),
    ('What is optimistic UI?', 'Update the UI before a server response, then confirm or roll back on failure.'),
    ('What is React Query?', 'A popular server-state library for caching, fetching, invalidation, and request status.'),
    ('Client state versus server state?', 'Client state is local UI data; server state is remote cached data that can become stale.'),
    ('What is Redux?', 'A predictable state-management library using a central store, actions, and reducers.'),
    ('What is Redux Toolkit?', 'The recommended Redux approach that reduces boilerplate and includes useful defaults.'),
    ('What is an action in Redux?', 'A plain object describing an event, commonly with `type` and payload.'),
    ('What is a reducer?', 'A pure function that computes next state from current state and an action.'),
    ('What is immutability in Redux?', 'Creating new state objects rather than changing existing state directly.'),
    ('What is accessibility in React?', 'Using semantic HTML, correct labels, keyboard support, focus management, and accessible names.'),
    ('How do you optimize a React app?', 'Measure first, then reduce unnecessary renders, split code, virtualize long lists, and optimize data loading.'),
    ('What is list virtualization?', 'Rendering only visible items in a large scrolling list to reduce DOM work.'),
    ('What is a performance profiler?', 'A tool that records component render timing so you can find actual bottlenecks.'),
    ('How do you test a React component?', 'Use a test runner and React Testing Library to test behavior from the user’s perspective.'),
    ('What should React tests avoid?', 'Avoid testing internal implementation details when visible behavior can be tested instead.'),
    ('What is snapshot testing?', 'Comparing rendered output to a stored snapshot; use it sparingly because broad snapshots are brittle.'),
    ('How do you type React with TypeScript?', 'Type props, state, events, refs, and component return values where inference is insufficient.'),
    ('What is a discriminated union for UI state?', 'A TypeScript union with a tag field that models states like loading, success, and error safely.'),
    ('What is an immutable update bug?', 'Mutating nested state can preserve references and cause incorrect rendering or memoization behavior.'),
    ('What is a controlled form validation pattern?', 'Store field values and errors in state, validate on change or submit, and connect errors to inputs.'),
    ('What is an accessible modal?', 'A dialog with focus moved inside, keyboard escape handling, focus restoration, and proper ARIA semantics.'),
    ('How do you share logic without sharing UI?', 'Extract that logic into a custom hook.'),
    ('What is the children-as-a-function pattern?', 'A component calls a function child with state or behavior so callers control rendering.'),
    ('What is a compound component?', 'Related components coordinate through shared context, such as Tabs, TabList, and TabPanel.'),
    ('What is controlled versus uncontrolled state at the component level?', 'A controlled component receives its value from a parent; an uncontrolled component owns its internal value.'),
    ('What makes a component reusable?', 'A small focused API, composition points, predictable behavior, accessibility, and minimal assumptions.'),
    ('What is forwardRef?', 'It lets a component pass a ref it receives to a child DOM node or component.'),
    ('What is useImperativeHandle?', 'It customizes the value exposed through a ref, and should be used sparingly.'),
    ('What is React DevTools?', 'A browser extension for inspecting component trees, props, state, and render performance.'),
    ('What is a hydration mismatch?', 'It occurs when server-rendered HTML differs from the first client render; make output deterministic.'),
    ('Why use semantic HTML before ARIA?', 'Native elements provide built-in keyboard and accessibility behavior that ARIA alone does not recreate.'),
    ('How do you prevent unnecessary child renders?', 'Keep props stable when useful, split components, and use memoization only after measuring a real issue.'),
]
