"""A curated set of common SQL interview prompts and short answers."""

SQL_QUESTIONS = [
    ('What is a primary key?', 'A column or columns that uniquely identify each row; it must be unique and not null.'),
    ('What is a foreign key?', 'A column that references a key in another table, enforcing a relationship between tables.'),
    ('What is a candidate key?', 'A minimal set of columns that can uniquely identify a row; one candidate key may become the primary key.'),
    ('What is a composite key?', 'A key made from two or more columns, used when no single column is unique.'),
    ('What is a surrogate key?', 'A generated identifier, such as an integer ID, with no business meaning.'),
    ('What is a unique constraint?', 'It prevents duplicate values; unlike a primary key, null handling depends on the database.'),
    ('What is a NOT NULL constraint?', 'It requires a column to contain a value for every row.'),
    ('What is a CHECK constraint?', 'It enforces a condition, for example `CHECK (price >= 0)`.'),
    ('What is a DEFAULT constraint?', 'It supplies a value when an insert omits that column.'),
    ('What is a database schema?', 'It is the logical structure of database objects such as tables, views, constraints, and routines.'),
    ('What is DDL?', 'Data Definition Language changes structure: `CREATE`, `ALTER`, `DROP`, and `TRUNCATE`.'),
    ('What is DML?', 'Data Manipulation Language changes rows: `INSERT`, `UPDATE`, and `DELETE`.'),
    ('What is DCL?', 'Data Control Language manages permissions, commonly `GRANT` and `REVOKE`.'),
    ('What is TCL?', 'Transaction Control Language manages transactions: `COMMIT`, `ROLLBACK`, and `SAVEPOINT`.'),
    ('What is the difference between DELETE, TRUNCATE, and DROP?', '`DELETE` removes selected rows, `TRUNCATE` removes all rows quickly, and `DROP` removes the table itself.'),
    ('What does SELECT DISTINCT do?', 'It removes duplicate result rows across the selected expressions.'),
    ('What is the WHERE clause for?', 'It filters rows before grouping and aggregation.'),
    ('What is the HAVING clause for?', 'It filters groups after `GROUP BY`, often using aggregate conditions.'),
    ('WHERE versus HAVING?', 'WHERE filters rows before aggregation; HAVING filters aggregated groups.'),
    ('What does ORDER BY do?', 'It sorts results ascending by default or descending with `DESC`.'),
    ('What does LIMIT do?', 'It restricts returned rows; some databases use `TOP` or `FETCH FIRST` instead.'),
    ('What is OFFSET used for?', 'It skips rows, commonly for pagination; keyset pagination can perform better on large tables.'),
    ('What does GROUP BY do?', 'It forms groups so aggregates such as `COUNT` or `SUM` are calculated per group.'),
    ('What does COUNT(*) count?', 'It counts rows, including rows where every selected column is null.'),
    ('COUNT(*) versus COUNT(column)?', 'COUNT(*) counts rows; COUNT(column) counts only non-null values in that column.'),
    ('What does SUM do?', 'It returns the total of numeric values, ignoring nulls.'),
    ('What does AVG do?', 'It returns the arithmetic mean of non-null numeric values.'),
    ('What do MIN and MAX do?', 'They return the smallest or largest non-null value in a group.'),
    ('How do you find duplicate values?', 'Group by the value and use `HAVING COUNT(*) > 1`.'),
    ('How do you remove duplicate rows safely?', 'Use `ROW_NUMBER()` to identify copies, then delete rows whose row number is greater than one.'),
    ('How do you find null values?', 'Use `WHERE column IS NULL`, never `= NULL`.'),
    ('How do you replace nulls in a query?', 'Use `COALESCE(column, fallback)`; many databases also offer vendor-specific functions.'),
    ('What does CASE do?', 'It provides conditional logic in SQL, such as categorizing rows inside a SELECT.'),
    ('What is an INNER JOIN?', 'It returns rows with matching join conditions in both tables.'),
    ('What is a LEFT JOIN?', 'It keeps every row from the left table and fills unmatched right-table columns with null.'),
    ('What is a RIGHT JOIN?', 'It keeps every row from the right table; it is often rewritten as a LEFT JOIN for readability.'),
    ('What is a FULL OUTER JOIN?', 'It returns matched rows plus unmatched rows from both tables.'),
    ('What is a CROSS JOIN?', 'It returns the Cartesian product: every left row paired with every right row.'),
    ('What is a SELF JOIN?', 'It joins a table to itself, for example to match employees to managers.'),
    ('What is a non-equi join?', 'It uses a condition other than equality, such as matching a value to a range.'),
    ('How do you find rows with no match?', 'LEFT JOIN the related table and filter where the right key is null.'),
    ('What is an anti join?', 'It returns left rows without a matching right row, commonly expressed with `NOT EXISTS`.'),
    ('NOT IN versus NOT EXISTS?', 'NOT EXISTS handles nulls more safely; NOT IN can return no rows if its subquery contains null.'),
    ('What is a subquery?', 'A query nested inside another query, used in expressions, filters, or FROM clauses.'),
    ('What is a correlated subquery?', 'It references a value from the outer query and may execute logically once per outer row.'),
    ('What is a CTE?', 'A Common Table Expression is a named temporary result defined with `WITH` for one statement.'),
    ('What is a recursive CTE?', 'A CTE that refers to itself, useful for hierarchies, trees, and generated sequences.'),
    ('What is a view?', 'A stored query presented like a table; it normally stores definition rather than data.'),
    ('What is a materialized view?', 'It stores query results physically and must be refreshed, trading freshness for faster reads.'),
    ('What is an index?', 'A data structure that speeds lookups and sorts at the cost of write overhead and storage.'),
    ('When can an index hurt performance?', 'On write-heavy tables, low-selectivity columns, or when too many indexes slow inserts and updates.'),
    ('What is a clustered index?', 'It determines or closely aligns with physical row order; terminology and limits vary by database.'),
    ('What is a nonclustered index?', 'It is a separate structure that stores indexed keys and row locators.'),
    ('What is a composite index?', 'An index on multiple columns; its leading-column order strongly affects which queries use it.'),
    ('What is a covering index?', 'An index containing all columns needed by a query, allowing an index-only scan in some databases.'),
    ('What is index selectivity?', 'It measures how well an index narrows rows; highly selective indexes usually help more.'),
    ('How do you inspect a query plan?', 'Use `EXPLAIN` or `EXPLAIN ANALYZE` and look for scans, joins, row estimates, and costs.'),
    ('What is a full table scan?', 'The database reads every table row, sometimes correct but costly on large selective queries.'),
    ('What is normalization?', 'It organizes data to reduce duplication and update anomalies through well-structured related tables.'),
    ('What is first normal form?', 'Each column holds atomic values and each row is uniquely identifiable.'),
    ('What is second normal form?', 'It is in first normal form and non-key columns depend on the entire key.'),
    ('What is third normal form?', 'It is in second normal form and non-key columns do not depend transitively on other non-key columns.'),
    ('When would you denormalize?', 'When measured read performance or reporting needs justify controlled duplication and update discipline.'),
    ('What is a transaction?', 'A sequence of operations treated as one unit of work that either commits or rolls back.'),
    ('What does ACID mean?', 'Atomicity, Consistency, Isolation, and Durability are core transaction guarantees.'),
    ('What is COMMIT?', 'It permanently makes the current transaction’s changes visible.'),
    ('What is ROLLBACK?', 'It discards uncommitted changes in the current transaction.'),
    ('What is a SAVEPOINT?', 'It marks a point inside a transaction that you can roll back to without discarding all work.'),
    ('What is a deadlock?', 'Transactions wait on each other’s locks; the database aborts one, so applications should retry safely.'),
    ('What is a lock?', 'It coordinates concurrent access to prevent conflicting changes or inconsistent reads.'),
    ('What are isolation levels?', 'They define visibility of concurrent changes, balancing correctness against concurrency.'),
    ('What is a dirty read?', 'Reading data another transaction changed but has not committed; many databases prevent this by default.'),
    ('What is a non-repeatable read?', 'Reading the same row twice and getting different committed values because another transaction updated it.'),
    ('What is a phantom read?', 'Repeating a predicate query and seeing new or removed matching rows from another transaction.'),
    ('What is a window function?', 'It calculates across related rows without collapsing them into one row per group.'),
    ('What does ROW_NUMBER do?', 'It assigns a unique sequential number within an ordered window.'),
    ('RANK versus DENSE_RANK?', 'RANK leaves gaps after ties; DENSE_RANK does not leave gaps.'),
    ('What does PARTITION BY do?', 'It restarts a window calculation for each partition, such as each customer.'),
    ('How do you find the second-highest salary?', 'Use `DENSE_RANK() OVER (ORDER BY salary DESC)` and filter rank two.'),
    ('How do you find the nth-highest salary?', 'Rank distinct salaries with DENSE_RANK and filter for the requested rank.'),
    ('How do you calculate a running total?', 'Use `SUM(amount) OVER (ORDER BY date ROWS UNBOUNDED PRECEDING)`.'),
    ('How do you compare a row to the previous row?', 'Use `LAG(column) OVER (PARTITION BY ... ORDER BY ...)`.'),
    ('How do you compare a row to the next row?', 'Use `LEAD(column) OVER (PARTITION BY ... ORDER BY ...)`.'),
    ('How do you find top N rows per group?', 'Use ROW_NUMBER or DENSE_RANK partitioned by group and filter ranks up to N.'),
    ('What is UNION?', 'It combines compatible results and removes duplicate rows.'),
    ('What is UNION ALL?', 'It combines compatible results and keeps duplicates, so it is usually faster.'),
    ('INTERSECT versus EXCEPT?', 'INTERSECT keeps common rows; EXCEPT returns rows in the first result but not the second.'),
    ('What is an upsert?', 'It inserts a row or updates an existing conflicting row, using syntax such as `ON CONFLICT`.'),
    ('How do you prevent SQL injection?', 'Use parameterized queries or prepared statements; never concatenate untrusted input into SQL.'),
    ('What is a prepared statement?', 'It separates SQL code from parameter values and can enable plan reuse.'),
    ('What is a stored procedure?', 'A named program stored in the database that can encapsulate multi-step database logic.'),
    ('What is a trigger?', 'Code that runs automatically when an insert, update, delete, or other database event occurs.'),
    ('What is referential integrity?', 'It keeps relationships valid, such as preventing an order from referencing a missing customer.'),
    ('What does ON DELETE CASCADE do?', 'Deleting a parent automatically deletes related child rows; use it only when the business rule allows it.'),
    ('What does ON DELETE SET NULL do?', 'Deleting a parent sets the child foreign-key column to null if that column permits null.'),
    ('How do you find customers with no orders?', 'LEFT JOIN orders to customers and filter rows where the order key is null.'),
    ('How do you find employees earning above their department average?', 'Join or correlate against an aggregate grouped by department, then compare each salary to that average.'),
    ('How do you find consecutive login days?', 'Use date differences with ROW_NUMBER or LAG to form contiguous-date groups.'),
    ('How do you paginate reliably?', 'Use a stable ORDER BY and prefer keyset pagination using the last seen key for large changing datasets.'),
    ('How do you optimize a slow query?', 'Measure with EXPLAIN ANALYZE, reduce rows early, index useful predicates, and avoid unnecessary work.'),
]
