"""100 curated common TypeScript interview questions, not a frequency ranking.

Examples assume strict type checking unless stated otherwise.
References: https://www.typescriptlang.org/docs/handbook/intro
https://www.typescriptlang.org/docs/handbook/utility-types
"""

TYPESCRIPT_QUESTIONS = [
    ('What does TypeScript add to JavaScript?', 'Static type checking and tooling for describing contracts before execution. Its type annotations are removed when producing JavaScript.'),
    ('Does TypeScript validate API responses at runtime?', 'No. Treat external data as unknown and validate its shape at the application boundary before using it.'),
    ('How do type inference and explicit annotations differ?', 'Inference derives a type from code; annotations declare a contract. Let local values infer naturally and annotate public boundaries when that improves clarity.'),
    ('Why prefer string over String in an annotation?', 'string describes primitive text values; String describes the boxed object type. Use lowercase primitive types for ordinary values.'),
    ('How do any and unknown differ?', 'any permits unchecked operations. unknown accepts arbitrary inputs but requires validation or narrowing before most operations.'),
    ('What does never represent?', 'A value that cannot exist, such as the result of a function that always throws or an exhausted union branch.'),
    ('How do void and undefined differ?', 'void expresses that a caller should ignore a return value. undefined describes the actual undefined value; the two have different function-assignability rules.'),
    ('What changes when strictNullChecks is enabled?', 'null and undefined are distinct types. A value must explicitly allow them, or be narrowed, before assignment or dereferencing.'),
    ('How do you type an array of numbers?', 'Use number[] or Array<number>. Both describe a mutable array whose elements are numbers.'),
    ('When should you use a tuple instead of an array?', 'Use a tuple for positional contracts: type Entry = [string, number]. It records the type of each position rather than one element type for all positions.'),
    ('How do union types work?', 'A value of A | B may satisfy either member. Only operations valid for the current narrowed type are allowed.'),
    ('How do intersection types work?', 'A value of A & B must satisfy both contracts. Incompatible property types can produce an impossible property type such as never.'),
    ('How would you restrict a status to three strings?', 'type Status = "idle" | "loading" | "done";\nThis prevents arbitrary strings from being assigned.'),
    ('Why can let status = "idle" infer string rather than "idle"?', 'The binding can later hold another string, so inference widens the literal. Use an explicit literal union when only selected values are valid.'),
    ('What does as const do?', 'It preserves literal types and gives object literals readonly properties and array literals readonly tuple types. It does not freeze objects at runtime.'),
    ('When would you choose an interface versus a type alias?', 'Both describe object shapes. Interfaces can be reopened through declaration merging; aliases also describe unions, tuples, and computed type expressions.'),
    ('What is structural typing?', 'Compatibility primarily depends on members rather than the declared name of a type. An object can satisfy an interface without explicitly implementing it.'),
    ('Why might an object literal fail an excess-property check?', 'Fresh object literals receive an extra check for unexpected properties, catching mistakes such as misspelled option names. This is not a universal exact-object guarantee.'),
    ('How do optional and required-with-undefined properties differ?', 'x?: number permits x to be absent. x: number | undefined requires the property to exist, although its value can be undefined.'),
    ('Does readonly make an object immutable?', 'It prevents assignment through that typed reference. It is not a runtime freeze and does not automatically make nested data readonly.'),
    ('How would you type a string-keyed numeric dictionary?', 'Use Record<string, number> or { [key: string]: number }. Consider noUncheckedIndexedAccess so missing keys are reflected as potentially undefined.'),
    ('Why must named properties agree with a string index signature?', 'The index signature also covers those names. In { [key: string]: number; name: string }, name violates the promise that every string-keyed value is numeric.'),
    ('What does keyof produce?', 'A union of the keys of a type. For {id: number; name: string}, keyof gives "id" | "name".'),
    ('What does typeof mean in a type position?', 'It obtains the static type of an existing value: const config = {port: 3000}; type Config = typeof config;'),
    ('How can you derive a union from a constant array?', 'const roles = ["admin", "editor"] as const;\ntype Role = typeof roles[number];'),
    ('How do you type a function taking two numbers and returning a number?', 'type Add = (a: number, b: number) => number;\nconst add: Add = (a, b) => a + b;'),
    ('How do optional parameters differ from default parameters?', 'An optional parameter may be undefined inside the function. A default initializer supplies a value when omitted or passed undefined, narrowing the parameter inside the body.'),
    ('How do you type a rest parameter?', 'function sum(...values: number[]): number {\n  return values.reduce((total, value) => total + value, 0);\n}'),
    ('When are function overloads useful?', 'When supported call shapes have different return contracts. Declare the public overloads and provide one implementation compatible with all of them.'),
    ('Can callers invoke a function using only its implementation signature?', 'With overload declarations, callers see the overload signatures. The implementation signature is used to check the body, not as an additional public overload.'),
    ('When is a union parameter preferable to overloads?', 'When all supported inputs have the same return contract and can be handled by narrowing. A union also accepts callers already holding a union-typed value.'),
    ('Why can a function returning a number be assigned to () => void?', 'The void callback contract says the caller ignores its return value. This allows callbacks such as array push, which returns a number, in contexts that ignore results.'),
    ('How do you type an async function returning a user?', 'async function loadUser(): Promise<User> { ... }\nThe promise resolves to User; the annotation does not validate the resolved data.'),
    ('How do you safely inspect a caught error?', 'Use if (error instanceof Error) before reading error.message, or handle non-Error thrown values separately. Under strict settings catch variables default to unknown.'),
    ('What is contextual typing?', 'The surrounding expected type informs inference. In [1, 2].map(value => value * 2), value is inferred as number.'),
    ('What problem do generics solve?', 'They preserve relationships between input and output types while allowing reuse, instead of discarding that information with any.'),
    ('Write a generic identity function.', 'function identity<T>(value: T): T {\n  return value;\n}'),
    ('Write a type-safe first-element function.', 'function first<T>(values: readonly T[]): T | undefined {\n  return values[0];\n}\nEmpty input is represented in the return type.'),
    ('How do generic constraints work?', 'T extends Contract restricts callers to compatible types and permits the implementation to use the members declared by Contract.'),
    ('Write a generic function that reads a valid object key.', 'function get<T, K extends keyof T>(object: T, key: K): T[K] {\n  return object[key];\n}'),
    ('How do generic parameter defaults work?', 'type Box<T = string> = {value: T};\nBox defaults to a string value, while Box<number> explicitly selects numbers.'),
    ('Why is returning any from a generic helper a problem?', 'It breaks the relationship the helper should preserve. Return T, T[K], or another appropriate derived type so callers retain useful checking.'),
    ('What does T[number] mean for an array type?', 'It extracts the array element type. For T = string[], T[number] is string; for a tuple it is the union of its element types.'),
    ('What is a mapped type?', 'It builds properties by iterating over a key union: type Flags<T> = { [K in keyof T]: boolean };'),
    ('How can a mapped type remove readonly modifiers?', 'type Mutable<T> = { -readonly [K in keyof T]: T[K] };\nThis changes the type view, not the object at runtime.'),
    ('What is a conditional type?', 'type Label<T> = T extends string ? "text" : "other";\nIt selects a type based on whether another type meets a constraint.'),
    ('What does infer do inside a conditional type?', 'It captures a type from a matched structure: type Item<T> = T extends readonly (infer U)[] ? U : T;'),
    ('Why can a conditional type distribute over a union?', 'When its checked side is a naked type parameter, it evaluates each union member separately. T extends string ? T : never filters a union to its string members.'),
    ('How do you prevent conditional-type distribution?', 'Wrap both sides in tuples: type IsString<T> = [T] extends [string] ? true : false;\nThe entire union is tested together.'),
    ('What are template literal types useful for?', 'They express string patterns: type Event = `on${"Click" | "Focus"}` gives "onClick" | "onFocus".'),
    ('What does Partial<T> do?', 'It makes all top-level properties optional. Useful for patch inputs; it does not recursively transform nested objects.'),
    ('What does Required<T> do?', 'It removes optional property modifiers at the top level. It does not create missing values at runtime.'),
    ('What does Pick<T, K> do?', 'It selects properties K from T: Pick<User, "id" | "name"> keeps those fields.'),
    ('What does Omit<T, K> do?', 'It removes selected keys from the type. It does not remove fields from an actual object or sanitize a response.'),
    ('What does Record<K, V> do?', 'It maps every key in K to V. Record<"en" | "fr", string> requires both named translations.'),
    ('What does Readonly<T> do?', 'It prevents top-level property assignment through that type; nested mutable values can remain mutable.'),
    ('How do Exclude and Extract differ?', 'Exclude<T, U> removes union members assignable to U; Extract<T, U> keeps them.'),
    ('What does NonNullable<T> do?', 'It removes null and undefined from T. It does not check or change runtime values.'),
    ('How do Parameters and ReturnType help avoid duplicated signatures?', 'Parameters<typeof fn> extracts an argument tuple; ReturnType<typeof fn> extracts the return type.'),
    ('What does Awaited<T> represent?', 'The recursively unwrapped result of awaiting a promise-like type, including handling unions.'),
    ('How do typeof guards narrow a union?', 'For value: string | number, typeof value === "string" allows string methods in that branch and number operations in the other.'),
    ('When would you narrow with instanceof?', 'When the value is a runtime class instance. value instanceof Date permits Date operations; interfaces cannot be used because they have no runtime constructor.'),
    ('How does the in operator help narrow object unions?', 'Checking "property" in value distinguishes members that may have that property. Optional properties can occur in both branches, so the result may still need further checks.'),
    ('What is a user-defined type predicate?', 'A function returning value is SomeType tells the checker how a boolean result narrows its argument. Its implementation must actually verify that contract.'),
    ('How do assertion functions differ from type predicates?', 'An assertion signature such as asserts value is string narrows after a successful call. The implementation should throw when the condition fails.'),
    ('What is a discriminated union?', 'A union whose members have distinct literal values on a shared field, such as kind. Checking that field identifies the corresponding member.'),
    ('How do you enforce exhaustive handling of a union?', 'In the remaining branch, assign the narrowed value to never or call a function accepting never. Adding an unhandled variant then produces a type error.'),
    ('Why can a truthiness guard mishandle a string value?', 'It excludes the empty string as well as nullish values. Check value !== null or value !== undefined when empty strings are valid.'),
    ('Does a type assertion convert a runtime value?', 'No. value as number does not parse text or validate data. Use Number(value) for conversion and explicit checks for validity.'),
    ('What risk does the non-null assertion operator introduce?', 'value! suppresses nullish checking without adding a runtime guard. If the assumption is wrong, execution can still fail.'),
    ('How does satisfies differ from an annotation or assertion?', 'It checks an expression against a target contract while retaining its resulting inferred type rather than replacing it with the target type. Contextual typing can still influence inference.'),
    ('Fix this unsafe operation: function upper(x: unknown) { return x.toUpperCase(); }', 'function upper(x: unknown): string {\n  if (typeof x !== "string") throw new TypeError("expected string");\n  return x.toUpperCase();\n}'),
    ('Why does const user = {name: "Ada"}; user.name = 3 fail?', 'The property is inferred as string. The const binding does not freeze properties, but their inferred types still constrain assignments.'),
    ('Why is const value: string & number = "x" invalid?', 'No ordinary value can be both primitive string and primitive number. This intersection reduces to never.'),
    ('Fix a possibly undefined result from users.find().', 'const user = users.find(item => item.id === id);\nif (!user) throw new Error("User not found");\n// user is now narrowed to an existing element.'),
    ('How do public, protected, and private class members differ?', 'public members are accessible everywhere, protected members inside the class and subclasses, and private members only inside the declaring class under type checking.'),
    ('How does private differ from JavaScript #private fields?', 'TypeScript private primarily restricts access during checking. #private fields enforce privacy at runtime using JavaScript semantics.'),
    ('What does implements verify on a class?', 'It checks that the instance shape meets an interface contract. It does not inject members or automatically infer parameter types for method implementations.'),
    ('When would you use an abstract class?', 'When subclasses should share implementation while being required to provide selected members. TypeScript prevents direct construction of an abstract class.'),
    ('What are constructor parameter properties?', 'An access or readonly modifier on a constructor parameter declares and initializes a member: constructor(public name: string) {}.'),
    ('What is the difference between static and instance members?', 'Static members belong to the constructor, while instance members belong to created objects. A class generic parameter is not available to its static members.'),
    ('Why use override and noImplicitOverride?', 'override records that a member replaces a base-class member. noImplicitOverride requires that declaration, helping detect accidental changes during refactoring.'),
    ('What does strictPropertyInitialization check?', 'It checks that instance fields are initialized or explicitly allow undefined, unless a definite-assignment assertion is used. That assertion does not initialize the field.'),
    ('When would you choose a string union instead of an enum?', 'A string union works well for JSON-friendly literal values with no emitted enum object. Enums can be useful when a runtime namespace of named values is desired.'),
    ('What runtime difference exists between numeric and string enums?', 'Ordinary numeric enums generate reverse mappings from numeric values to names. String enums do not generate those reverse mappings.'),
    ('What is a .d.ts file?', 'A declaration file describing types for existing JavaScript APIs. It provides compile-time contracts without implementing the runtime behavior.'),
    ('What does import type do?', 'It marks an import as type-only so it is removed from emitted JavaScript. The imported name cannot then be used as a runtime value.'),
    ('How do modules differ from namespaces?', 'Modules organize files through imports and exports and integrate with JavaScript tooling. Namespaces are a TypeScript construct often seen in older code or declarations.'),
    ('What is declaration merging?', 'Certain declarations with the same name combine, such as interfaces. Type aliases cannot be reopened this way; merged members must obey compatibility rules.'),
    ('How would you add type declarations for an existing library extension?', 'Use module augmentation targeting the module and interface being extended. Ensure the corresponding runtime extension actually exists; declarations do not implement it.'),
    ('What is tsconfig.json used for?', 'It defines the project files and compiler options, including strictness, module behavior, libraries, and emission settings.'),
    ('How do target and lib differ?', 'target controls the JavaScript version used for emitted syntax. lib controls available built-in API declarations; it does not install runtime polyfills.'),
    ('How do module and moduleResolution differ?', 'module controls module-related emit and semantics; moduleResolution controls how imports are located. Choose a compatible pair for the actual runtime or bundler.'),
    ('What does the strict compiler option enable?', 'A family of stricter checks, including implicit-any and nullability checks. Some additional checks, such as noUncheckedIndexedAccess, must be enabled separately.'),
    ('What does noUncheckedIndexedAccess catch?', 'It includes undefined for potentially absent indexed values, such as array lookups or dictionary entries, forcing callers to handle missing data.'),
    ('What does exactOptionalPropertyTypes change?', 'An optional property can be absent, but assigning undefined requires the declared value type to allow it. Reading an optional property can still yield undefined.'),
    ('How do noEmit and noEmitOnError differ?', 'noEmit disables output entirely. noEmitOnError prevents output when diagnostics report errors; otherwise JavaScript emission and successful type checking are separate concerns.'),
    ('How do @ts-expect-error and @ts-ignore differ?', '@ts-expect-error reports a problem if the next line no longer has an error, making it useful for type regression tests. @ts-ignore does not detect that change.'),
    ('How would you migrate a JavaScript project incrementally?', 'Start with allowJs, optionally checkJs, and migrate a small boundary at a time. Add explicit external-data validation, reduce any usage, and tighten compiler options gradually.'),
    ('How would you model an API result without optional success and error fields?', 'type Result<T> =\n  | {ok: true; data: T}\n  | {ok: false; error: string};\nCheck result.ok to access only the fields valid for that branch. Validate the response before treating external JSON as this type.'),
]
